name: CI Sistema PayAccount

on:
  push:
    branches:
      - main
      - hml
  #pull_request:
   # branches:
    #  - main

env:
  PYTHON_VERSION: '3.8'
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_REPO }}

permissions:
  contents: write
  packages: write

jobs:
  build-hml:
    if: github.ref_name == 'hml'
    runs-on: ubuntu-latest
    environment: PROD   
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}


      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/hml'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image hml
        if: github.ref == 'refs/heads/hml'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:hml-${{ github.run_id }}

  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: PROD
    name: Build e Push PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Detect bump type
        id: bump
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Ãšltimo commit: $COMMIT_MSG"

                    
          if echo "$COMMIT_MSG" | grep -iq "#major"; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MSG" | grep -iq "#patch"; then
            echo "bump=patch" >> $GITHUB_OUTPUT
          else
            echo "bump=minor" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and create tag PROD
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.bump.outputs.bump }}
          tag_prefix: v

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Prod image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.tag_version.outputs.new_tag }}
            ${{ env.DOCKER_IMAGE }}:latest